version: "3"
services:
  redis:
    image: redis:alpine
    restart: always

  web:
    build: .
    env_file: .env
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - redis

  worker:
    build: .
    env_file: .env
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    command: celery -A app.execution.tasks worker --loglevel=info
    depends_on:
      - redis
