site_name: CCXT FastAPI Webhook
repo_url: https://github.com/your-username/ccxt-trading-webhook
edit_uri: edit/main/docs/

theme:
  name: material

nav:
  - Home: index.md
  - User Guide:
      - Getting Started: getting-started.md
      - Authentication: authentication.md
      - TradingView Integration: tradingview.md
  - Modules:
      - Overview: features.md
      - Identity:
          - Overview: modules/identity/index.md
          - Design: modules/identity/design.md
          - Implementation Plan: modules/identity/implementation-plan.md
      - Wallet:
          - Overview: modules/wallet/index.md
          - Design: modules/wallet/design.md
      - Marketplace: modules/marketplace/index.md
      - Subscription: modules/subscription/index.md
      - Execution: modules/execution/index.md
      - Ledger: modules/ledger/index.md
      - Risk: modules/risk/index.md
      - Dashboard: modules/dashboard/index.md
      - Compliance: modules/compliance/index.md
  - Reference:
      - API Reference: api-reference.md
  - Deployment:
      - Deployment Guide: deployment.md

plugins:
  - search
  - openapi_markdown:
      openapi_file: docs/openapi.json
      output_file: docs/api-reference.md
