site_name: CCXT FastAPI Webhook
repo_url: https://github.com/your-username/ccxt-trading-webhook
edit_uri: edit/main/docs/

theme:
  name: material

nav:
  - Home: index.md
  - User Guide:
      - Getting Started: getting-started.md
      - Authentication: authentication.md
      - TradingView Integration: tradingview.md
      - Feature Overview: features.md
  - Reference:
      - API Reference: api-reference.md
  - Design:
      - Identity Module: identity-module-design.md
      - Identity Implementation Plan: identity-implementation-plan.md
  - Deployment:
      - Deployment Guide: deployment.md

plugins:
  - search
  - openapi_markdown:
      openapi_file: docs/openapi.json
      output_file: docs/api-reference.md
