site_name: CCXT FastAPI Webhook
repo_url: https://github.com/your-username/ccxt-trading-webhook
edit_uri: edit/main/docs/

theme:
  name: material

nav:
  - Home: index.md
  - User Guide:
      - Getting Started: getting-started.md
      - Authentication: authentication.md
      - TradingView Integration: tradingview.md
  - Modules:
      - Overview: features.md
      - Identity:
          - Module Guide: modules/identity.md
          - Design Doc: identity_module_design.md
          - Implementation Plan: identity-implementation-plan.md
      - Wallet:
          - Module Guide: modules/wallet.md
          - Design Doc: wallet_module_design.md
      - Marketplace: modules/marketplace.md
      - Subscription: modules/subscription.md
      - Execution: modules/execution.md
      - Ledger: modules/ledger.md
      - Risk: modules/risk.md
      - Dashboard: modules/dashboard.md
      - Compliance: modules/compliance.md
  - Reference:
      - API Reference: api-reference.md
  - Deployment:
      - Deployment Guide: deployment.md

plugins:
  - search
  - openapi_markdown:
      openapi_file: docs/openapi.json
      output_file: docs/api-reference.md
